# Site settings

title: oy.
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/XRD-WAXS-polymers"
url: "http://adotsenko3.github.io"
github_username:  adotsenko3
project_repository: XRD-WAXS-polymers
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
